### ISSUE TITLE
heos_player fails when performing any commands because of a lack of group ID

### ISSUE THREAD

**Issue by ping13** [ping13/heospy#10]
heos_player fails when performing any commands because of a lack of group ID failing at line 215, in _update_groups_players.

for example
```
2019-04-17 07:43:08,254 DEBUG telnet request heos://player/get_groups
2019-04-17 07:43:08,255 DEBUG starting response loop
2019-04-17 07:43:08,262 DEBUG ... unfinished response: {"heos": {"command": "player/get_groups", "result"
2019-04-17 07:43:08,264 DEBUG found valid JSON: {"payload": [], "heos": {"message": "", "command": "player/get_groups", "result": "success"}}
2019-04-17 07:43:08,265 DEBUG I assume this is the final response: {u'payload': [], u'heos': {u'message': u'', u'command': u'player/get_groups', u'result': u'success'}}
2019-04-17 07:43:08,266 DEBUG found valid response: {"payload": [], "heos": {"message": "", "command": "player/get_groups", "result": "success"}}
2019-04-17 07:43:08,267 ERROR I couldn't find a list of groups.
Traceback (most recent call last):
File "/usr/local/bin/heos_player", line 11, in <module>
load_entry_point('heospy==0.1.3', 'console_scripts', 'heos_player')()
File "build/bdist.linux-armv7l/egg/heospy/heos_player.py", line 385, in main
File "build/bdist.linux-armv7l/egg/heospy/heos_player.py", line 117, in __init__
File "build/bdist.linux-armv7l/egg/heospy/heos_player.py", line 215, in _update_groups_players
heospy.heos_player.HeosPlayerGeneralException: I couldn't find a list of groups.
```

(Thanks, Ian)

**Comment by ping13** [comment]
In line 204, the payload may be empty:

```python
            result = self.telnet_request("player/get_{}".format(aggregate)).get("payload")
```

This should not result in an exception for a group, only for players. Maybe something like this:

```python
            else:
                msg = "I couldn't find a list of {}.".format(aggregate)
                if aggregate == "groups":
                    logging.warn(msg)
                else:
                    logging.error(msg)
                    raise HeosPlayerGeneralException(msg)
```
