### ISSUE TITLE
Error 1 with the install of heospy

### ISSUE THREAD

**Issue by mcmellow** [ping13/heospy#15]
Running: **pip3 install heospy**  or  **python3 -m pip install heospy**  results in the same error.
There is something wrong in line 19 of setup.py  See error log below.
     No such file or directory: 'Readme.md'
What can be changed in setup.py?

```
pi@mcmellow-pi:~ $ python3 -m pip install heospy
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting heospy
  Using cached heospy-0.1.4.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bk3_spkt/heospy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bk3_spkt/heospy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bk3_spkt/heospy/pip-egg-info
         cwd: /tmp/pip-install-bk3_spkt/heospy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bk3_spkt/heospy/setup.py", line 19, in <module>
        long_description=open('Readme.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'Readme.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mcmellow** [comment]
After a long and extensive google search found this work around.

```
python3 -m pip install 'git+https://github.com/ping13/heospy.git'

With the following warning
  WARNING: The script heos_player is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
This worked OK for me on a Raspberry Pi 3B+  with Raspbian Buster

**Comment by ping13** [comment]
Thank your patience and sorry for not getting back to you earlier. 
I’ve redone the installation procedure and this should be now fixed. The latest version should be available on PyPi now and should be installable with `pip install heospy` again.
